#!/usr/bin/env bash
set -euo pipefail

# This script lives in tools/; brand source assets live in resources/branding/ and
# all generated outputs land in the module trees at the repo root (one level up).
#
# logo.svg is the SINGLE hand-edited source of truth (the bare gradient waveform).
# icon.svg and banner.svg are GENERATED from it by the compose step below and then
# consumed like any other input — so the waveform can never drift between them.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
LOGO="$REPO_ROOT/resources/branding/logo.svg"
SVG="$REPO_ROOT/resources/branding/icon.svg"
BANNER_SVG="$REPO_ROOT/resources/branding/banner.svg"
ANDROID_RES="$REPO_ROOT/androidApp/src/main/res"
SHARED_RES="$REPO_ROOT/shared/src/androidMain/res"
COMPOSE_RES="$REPO_ROOT/shared/src/commonMain/composeResources/drawable"
DESKTOP_RES="$REPO_ROOT/desktopApp/src/main/resources"
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

for cmd in inkscape magick python3; do
    command -v "$cmd" >/dev/null || { echo "Error: '$cmd' not found"; exit 1; }
done

echo "Composing icon.svg + banner.svg from logo.svg (single source of truth)..."
# Pull the <defs> (gradient) and the single waveform <path> out of logo.svg and splice
# them into two self-contained composites: icon.svg = navy tile + waveform; banner.svg =
# navy 640x360 + waveform (scaled 0.5 into a 256px box at 52,52) + the "Yama" wordmark.
# Self-contained (no external refs) so the README raw-URL fetch and inkscape both work.
LOGO="$LOGO" ICON_OUT="$SVG" BANNER_OUT="$BANNER_SVG" python3 << 'PYEOF'
import os, re

logo = open(os.environ['LOGO']).read()
defs = re.search(r"<defs\b.*?</defs>", logo, re.S)
path = re.search(r"<path\b.*?/>",      logo, re.S)
if not defs or not path:
    raise SystemExit("logo.svg: expected a <defs> block and exactly one <path>")
DEFS, PATH = defs.group(0).strip(), path.group(0).strip()

# NB: no "--" inside the comment body; strict XML parsers (expat/ElementTree, used by
# the vector-drawable step below) reject a double hyphen anywhere but the closing "-->".
HEAD = ('<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n'
        '<!-- GENERATED by tools/generate_icons.sh from logo.svg. Do not edit by hand. -->')
NS = ('xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" '
      'xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" '
      'xmlns:xlink="http://www.w3.org/1999/xlink" '
      'xmlns="http://www.w3.org/2000/svg"')

# The wordmark is banner chrome (not part of the logo), so it lives here as a constant.
TEXT = ('<text xml:space="preserve" '
        'style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;'
        "font-size:90.3111px;font-family:'Noto Sans';-inkscape-font-specification:'Noto Sans Bold';"
        'writing-mode:lr-tb;direction:ltr;fill:#eae9fd;fill-opacity:1;stroke:#ffffff;stroke-width:7.9375;'
        'stroke-linecap:round;stroke-linejoin:round" x="346.14731" y="211.78934" id="text1">'
        '<tspan sodipodi:role="line" id="tspan1" '
        'style="font-style:normal;font-variant:normal;font-weight:bold;font-stretch:normal;'
        "font-size:90.3111px;font-family:'Noto Sans';-inkscape-font-specification:'Noto Sans Bold';"
        'fill:#eae9fd;fill-opacity:1;stroke:none;stroke-width:7.9375;stroke-opacity:1" '
        'x="346.14731" y="211.78934">Yama</tspan></text>')

icon = f'''{HEAD}
<svg width="512" height="512" viewBox="0 0 512 512" version="1.1" id="svg1" {NS}>
  {DEFS}
  <rect style="fill:#140e30;stroke-width:10;stroke-linecap:round" id="rect1" width="512" height="512" x="0" y="0" inkscape:label="background" />
  <g inkscape:label="Layer 1" inkscape:groupmode="layer" id="layer1">
    {PATH}
  </g>
</svg>
'''

banner = f'''{HEAD}
<svg width="640" height="360" viewBox="0 0 640 360" version="1.1" id="svg1" {NS}>
  {DEFS}
  <rect style="fill:#140e30;stroke-width:9.37498;stroke-linecap:round" id="rect1" width="640" height="360" x="0" y="0" inkscape:label="background" />
  <g inkscape:label="Layer 1" inkscape:groupmode="layer" id="layer1">
    <g transform="translate(52,52) scale(0.5)">
      {PATH}
    </g>
  </g>
  {TEXT}
</svg>
'''

open(os.environ['ICON_OUT'],   'w').write(icon)
open(os.environ['BANNER_OUT'], 'w').write(banner)
print(f"  icon.svg + banner.svg regenerated from logo.svg")
PYEOF

echo "Android legacy mipmap icons (pre-API 26 fallback)..."
declare -A LEGACY=([mdpi]=48 [hdpi]=72 [xhdpi]=96 [xxhdpi]=144 [xxxhdpi]=192)
for density in "${!LEGACY[@]}"; do
    size=${LEGACY[$density]}
    png="$TMP/legacy_${density}.png"
    inkscape "$SVG" --export-type=png --export-filename="$png" -w "$size" -h "$size" 2>/dev/null
    cp "$png" "$ANDROID_RES/mipmap-${density}/ic_launcher.png"
    cp "$png" "$ANDROID_RES/mipmap-${density}/ic_launcher_round.png"
    rm -f "$ANDROID_RES/mipmap-${density}/ic_launcher_foreground.png"
    echo "  mipmap-$density: ${size}x${size}"
done

echo "Android vector drawables..."
# ic_launcher_foreground.xml — gradient waveform, used by launcher adaptive icon and splash screen
# ic_launcher_monochrome.xml — white waveform, used by Android 13+ themed/monochrome icons
# ic_notification_waveform.xml — white waveform, full-canvas, for the Media3 notification small icon
# All three are waveform-ONLY (no background), so they derive straight from logo.svg — the parser
# reads just the <path>/<gradient>/viewBox and never the tile background.
# NB: plain drawable/ (not drawable-v24/): the foreground is only referenced by the API-26+
# adaptive icon, so the inline <gradient> (runtime-supported since API 24) never loads on an
# older API — no -v24 qualifier needed, and this matches where @drawable/ic_launcher_foreground
# actually resolves in the repo.
SVG="$LOGO" \
FG_OUT="$ANDROID_RES/drawable/ic_launcher_foreground.xml" \
MONO_OUT="$ANDROID_RES/drawable/ic_launcher_monochrome.xml" \
NOTIF_OUT="$SHARED_RES/drawable/ic_notification_waveform.xml" \
python3 << 'PYEOF'
import xml.etree.ElementTree as ET, os, re, sys

SVG_PATH  = os.environ['SVG']
FG_OUT    = os.environ['FG_OUT']
MONO_OUT  = os.environ['MONO_OUT']
NOTIF_OUT = os.environ['NOTIF_OUT']
NS        = 'http://www.w3.org/2000/svg'

tree = ET.parse(SVG_PATH)
root = tree.getroot()

path_elem = next(
    (e for e in root.iter(f'{{{NS}}}path')
     if 'linearGradient' in e.get('style', '')),
    None)
if path_elem is None:
    sys.exit("No gradient-stroke path found in SVG")

style     = path_elem.get('style', '')
path_data = path_elem.get('d', '')

def css(prop, default):
    m = re.search(rf'{prop}:([^;]+)', style)
    return m.group(1).strip() if m else default

stroke_width   = css('stroke-width', '5')
stroke_linecap = css('stroke-linecap', 'round')

grad_stops = grad_coords = None
for g in root.iter(f'{{{NS}}}linearGradient'):
    if g.findall(f'{{{NS}}}stop'):
        grad_stops = g
    if g.get('gradientUnits') == 'userSpaceOnUse':
        grad_coords = g

if grad_stops is None or grad_coords is None:
    sys.exit("Could not find gradient in SVG")

stop_lines = []
for stop in grad_stops.findall(f'{{{NS}}}stop'):
    s      = stop.get('style', '')
    offset = stop.get('offset', '0')
    color  = re.search(r'stop-color:#([0-9a-fA-F]+)', s)
    alpha  = re.search(r'stop-opacity:([\d.]+)', s)
    color  = color.group(1) if color else '000000'
    alpha  = round(float(alpha.group(1)) * 255) if alpha else 255
    stop_lines.append(
        f'            <item android:offset="{offset}" android:color="#{alpha:02x}{color}"/>')

vb = root.get('viewBox', '0 0 512 512').split()
vw, vh = vb[2], vb[3]
x1 = grad_coords.get('x1', '0')
y1 = grad_coords.get('y1', '0')
x2 = grad_coords.get('x2', vw)
y2 = grad_coords.get('y2', '0')
stops_str = '\n'.join(stop_lines)

cx, cy = float(vw) / 2, float(vh) / 2

# Launcher icons scale the waveform to 2/3 (the adaptive-icon safe zone) so it
# clears the circular launcher and splash-screen masks. The notification small
# icon has no mask, so it fills the full canvas (scale 1.0) to read larger in
# the status bar.
def header(scale):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="{vw}"
    android:viewportHeight="{vh}">
    <group
        android:pivotX="{cx:.3f}"
        android:pivotY="{cy:.3f}"
        android:scaleX="{scale:.6f}"
        android:scaleY="{scale:.6f}">'''

HEADER = header(2.0 / 3.0)

PATH_ATTRS = f'''        <path
            android:pathData="{path_data}"
            android:fillColor="#00000000"
            android:strokeWidth="{stroke_width}"
            android:strokeLineCap="{stroke_linecap}"'''

FOOTER = '''    </group>
</vector>'''

def write(path, xml):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w') as f:
        f.write(xml)
    print(f"  {path}")

write(FG_OUT, f'''{HEADER}
{PATH_ATTRS}>
            <aapt:attr name="android:strokeColor">
                <gradient
                    android:startX="{x1}"
                    android:startY="{y1}"
                    android:endX="{x2}"
                    android:endY="{y2}"
                    android:type="linear">
{stops_str}
                </gradient>
            </aapt:attr>
        </path>
{FOOTER}''')

write(MONO_OUT, f'''{HEADER}
{PATH_ATTRS}
            android:strokeColor="#FFFFFFFF" />
{FOOTER}''')

# Media3 playback-notification small icon (shared module): same white waveform,
# but full-canvas (no safe-zone shrink) and tinted by the system.
write(NOTIF_OUT, f'''{header(1.0)}
{PATH_ATTRS}
            android:strokeColor="#FFFFFFFF" />
{FOOTER}''')
PYEOF

echo "Android adaptive icon XML..."
ADAPTIVE_ICON='<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@drawable/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>'
for name in ic_launcher ic_launcher_round; do
    echo "$ADAPTIVE_ICON" > "$ANDROID_RES/mipmap-anydpi-v26/${name}.xml"
    echo "  mipmap-anydpi-v26/${name}.xml"
done

echo "Cleaning up stale files..."
rm -f "$ANDROID_RES/drawable/ic_splash_icon.xml"
echo "  removed ic_splash_icon.xml"

echo "Android TV banner..."
mkdir -p "$ANDROID_RES/drawable-xhdpi"
inkscape "$BANNER_SVG" --export-type=png \
    --export-filename="$ANDROID_RES/drawable-xhdpi/tv_banner.png" \
    -w 640 -h 360 2>/dev/null
echo "  drawable-xhdpi/tv_banner.png (640x360)"

echo "Login hero logo (Compose shared resources)..."
# The gradient waveform mark ONLY — it sits on transparency beside the in-app "Yama"
# wordmark in the login screen's LoginHeader (which pairs it with a themed Text, not
# baked-in copy). logo.svg IS the background-free waveform, so we export it directly —
# no layer-id trick needed. Compose Resources can't load .svg, so ship a 512px PNG.
mkdir -p "$COMPOSE_RES"
inkscape "$LOGO" --export-area-page --export-type=png \
    --export-filename="$COMPOSE_RES/yama_logo.png" -w 512 -h 512 2>/dev/null
echo "  yama_logo.png (512x512, transparent — waveform only)"

echo "Desktop icons..."
mkdir -p "$DESKTOP_RES"
inkscape "$SVG" --export-type=png --export-filename="$DESKTOP_RES/icon.png" -w 512 -h 512 2>/dev/null
magick "$DESKTOP_RES/icon.png" \
    -define icon:auto-resize=256,128,64,48,32,16 \
    "$DESKTOP_RES/icon.ico"
echo "  icon.png (512x512), icon.ico (multi-size)"

echo "Desktop system-tray icon..."
# The full icon.png tile is illegible at a 22-32px tray size, so the tray uses the waveform ALONE.
# Derived from logo.svg on the fly (no separate source to drift): thicken the stroke 1.8x for
# small-size legibility, and make the gradient's two end stops opaque (the app icon's fade-to-
# transparent ends dissolve at tray size, especially on light panels). Consumed by DesktopTray.
LOGO="$LOGO" TRAY_SVG="$TMP/tray.svg" python3 << 'PYEOF'
import os, re
svg = open(os.environ['LOGO']).read()
m = re.search(r'stroke-width:([0-9.]+)', svg)
if not m:
    raise SystemExit("logo.svg: no stroke-width in the waveform style")
svg = svg.replace(f'stroke-width:{m.group(1)}', f'stroke-width:{round(float(m.group(1)) * 1.5, 4)}')
svg = svg.replace('stop-opacity:0;', 'stop-opacity:1;')   # solid ends (both end stops)
open(os.environ['TRAY_SVG'], 'w').write(svg)
PYEOF
inkscape "$TMP/tray.svg" --export-area-page --export-type=png \
    --export-filename="$DESKTOP_RES/tray.png" -w 256 -h 256 2>/dev/null
echo "  tray.png (256x256, waveform only, solid ends, 1.8x stroke)"

echo "Done."
